// apps/web/src/app/[gameCode]/song/page.tsx
"use client";

import Link from "next/link";
import { Suspense, useMemo } from "react";
import { notFound, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { useGameContext } from "@/contexts/GameContext";
import { useGameDataQuery, useCurrentData } from "@/hooks/useGameDataQuery";
import { useGameLookups } from "@/hooks/useGameLookups";
import { useSheetDialogStore } from "@/stores/sheetDialog";
import { noteTypesByGame } from "@/data/gameFeatures";
import { validateNoteCounts } from "@/lib/utils/sheet";
import { Button } from "@/components/ui/button";

function SongDetail() {
  const t = useTranslations();
  const params = useSearchParams();
  const { gameCode } = useGameContext();
  const query = useGameDataQuery();
  const data = useCurrentData();
  const lookup = useGameLookups();
  const open = useSheetDialogStore((state) => state.open);
  const songId = params.get("id");
  const song = data.songs.find((entry) => entry.songId === songId);
  const noteKeys = useMemo(
    () =>
      gameCode === "ongeki"
        ? ["total", "bell"]
        : noteTypesByGame[gameCode]
          ? ["total", ...noteTypesByGame[gameCode]]
          : [],
    [gameCode],
  );
  if (query.isSuccess && !song) notFound();
  if (!song)
    return <div className="p-10 text-center">{t("description.loading")}</div>;
  return (
    <div className="mx-auto max-w-screen-xl px-4 py-6 sm:px-8">
      <Button variant="outline" asChild>
        <Link href={`/${gameCode}/songs/`}>← {t("ui.goBack")}</Link>
      </Button>
      <h1 className="my-6 text-3xl font-semibold">{song.title}</h1>
      <div className="grid gap-6 md:grid-cols-[300px_1fr] md:items-start">
        <img
          src={song.imageUrl}
          alt={song.title}
          className="h-[300px] w-[300px] object-contain"
        />
        <table className="border-collapse text-sm">
          <tbody>
            {[
              [t("term.category"), song.category],
              [t("term.title"), song.title],
              [t("term.artist"), song.artist],
              [t("term.bpm"), song.bpm],
              [t("term.releaseDate"), song.releaseDate?.replaceAll("-", "/")],
              [t("term.version"), song.version],
            ].map(([key, value]) => (
              <tr
                key={key as string}
                className="border-b border-[var(--border)]"
              >
                <th className="px-3 py-2 text-left">{key}</th>
                <td className="px-3 py-2">{value ?? "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <h2 className="my-6 text-2xl font-semibold">
        {t("page.songs.sheetData")}
      </h2>
      <div className="overflow-x-auto">
        <table className="min-w-[800px] border-collapse text-center text-sm">
          <thead>
            <tr className="bg-black/5 dark:bg-white/5">
              <th className="px-2 py-2">{t("term.type")}</th>
              <th className="px-2 py-2">{t("term.difficulty")}</th>
              <th className="px-2 py-2">{t("term.level")}</th>
              <th className="px-2 py-2">{t("term.internalLevel")}</th>
              {noteKeys.map((key) => (
                <th key={key} className="px-2 py-2">
                  {key === "total" ? t("term.totalNotes") : key.toUpperCase()}
                </th>
              ))}
              <th className="px-2 py-2">{t("term.noteDesigner")}</th>
            </tr>
          </thead>
          <tbody>
            {song.sheets.map((sheet) => (
              <tr
                key={sheet.sheetExpr}
                className="border-b border-[var(--border)]"
              >
                <td className="px-2 py-2">{lookup.getTypeAbbr(sheet.type)}</td>
                <td className="px-2 py-2">
                  <button
                    type="button"
                    className="font-bold underline"
                    style={{
                      color: lookup.getDifficultyColor(sheet.difficulty),
                    }}
                    onClick={() => open(sheet)}
                  >
                    {lookup.getDifficultyName(sheet.difficulty)}
                  </button>
                </td>
                <td className="px-2 py-2">{sheet.level}</td>
                <td className="px-2 py-2">{sheet.internalLevel ?? "—"}</td>
                {noteKeys.map((key) => (
                  <td key={key} className="px-2 py-2">
                    {sheet.noteCounts?.[key] ?? "—"}
                    {key === "total" &&
                      !validateNoteCounts(sheet, gameCode) && (
                        <span title={t("description.invalidNoteCounts")}>
                          {" "}
                          ⚠
                        </span>
                      )}
                  </td>
                ))}
                <td className="px-2 py-2">{sheet.noteDesigner}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function SongPage() {
  return (
    <Suspense fallback={<div className="p-10 text-center">Loading…</div>}>
      <SongDetail />
    </Suspense>
  );
}

// pages/_gameCode/song.vue
<script setup lang="ts">
/* eslint-disable import/first, import/no-duplicates */
import { computed, useRoute, useMeta as useHead, useContext } from '@nuxtjs/composition-api';
import { useDataStore } from '~/stores/data';
import useI18n from '~/composables/useI18n';
import useGameInfo from '~/composables/useGameInfo';
import useGameData from '~/composables/useGameData';
import useSheetDialog from '~/composables/useSheetDialog';
import LoadingStatus from '~/enums/LoadingStatus';
import { validateNoteCounts, PageNotFoundError } from '~/utils';

const context = useContext();
const i18n = useI18n();
const route = useRoute();
const dataStore = useDataStore();
const {
  gameCode,
} = useGameInfo();
const {
  getTypeAbbr,
  getDifficultyColor,
  getDifficultyName,
} = useGameData();
const {
  viewSheet,
} = useSheetDialog();

const song = computed(
  () => {
    const songId = route.value.query.id;
    const foundSong = dataStore.currentData.songs.find((song) => song.songId === songId) ?? null;

    if (
      songId !== undefined && foundSong === null
      && dataStore.currentLoadingStatus === LoadingStatus.LOADED
    ) {
      context.error(new PageNotFoundError());
    }

    return foundSong;
  },
);

const extraSheetHeaders = computed(() => {
  if (gameCode.value === 'maimai') {
    return ['total', 'tap', 'hold', 'slide', 'touch', 'break']
      .map((key) => ({
        key,
        title: key !== 'total' ? key.toUpperCase() : i18n.t('term.totalNotes'),
        get: (sheet: Sheet) => sheet.noteCounts?.[key],
      }));
  }
  if (gameCode.value === 'chunithm') {
    return ['total', 'tap', 'hold', 'slide', 'air', 'flick']
      .map((key) => ({
        key,
        title: key !== 'total' ? key.toUpperCase() : i18n.t('term.totalNotes'),
        get: (sheet: Sheet) => sheet.noteCounts?.[key],
      }));
  }
  if (gameCode.value === 'ongeki') {
    return ['total', 'bell']
      .map((key) => ({
        key,
        title: key !== 'total' ? key.toUpperCase() : i18n.t('term.totalNotes'),
        get: (sheet: Sheet) => sheet.noteCounts?.[key],
      }));
  }

  return [];
});

useHead(() => ({
  title: `${song.value?.title} | ${i18n.t('page-title.song')}`,
}));
</script>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api';
import type { Sheet } from '~/types';

export default defineComponent({
  name: 'GameSongPage',
  head: {},
});
</script>

<template>
  <v-container class="pa-4 pa-sm-8">
    <v-btn
      color="secondary"
      outlined
      exact
      :to="{ name: 'gameCode-songs' }"
    >
      <v-icon left>
        mdi-keyboard-return
      </v-icon>
      <span v-text="$t('ui.goBack')" />
    </v-btn>

    <template v-if="song != null">
      <h1 class="my-6">
        <span v-text="song.title" />
      </h1>

      <v-row>
        <v-col cols="12" sm="auto" class="d-flex align-center">
          <img
            :src="song.imageUrl"
            :alt="song.title"
            style="width: 300px; height: 300px; object-fit: contain; vertical-align: middle;"
          >
        </v-col>
        <v-col cols="12" sm="auto">
          <v-simple-table class="text-center">
            <tbody>
              <tr>
                <th>
                  <span v-text="$t('term.category')" />
                </th>
                <td>
                  <span v-text="song.category" />
                </td>
              </tr>
              <tr>
                <th>
                  <span v-text="$t('term.title')" />
                </th>
                <td>
                  <span v-text="song.title" />
                </td>
              </tr>
              <tr>
                <th>
                  <span v-text="$t('term.artist')" />
                </th>
                <td>
                  <span v-text="song.artist" />
                </td>
              </tr>
              <tr>
                <th>
                  <span v-text="$t('term.bpm')" />
                </th>
                <td>
                  <span v-text="song.bpm" />
                </td>
              </tr>
              <tr>
                <th>
                  <span v-text="$t('term.releaseDate')" />
                </th>
                <td>
                  <span>{{ (song.releaseDate ?? '').replaceAll('-', '/') }}</span>
                </td>
              </tr>
              <tr>
                <th>
                  <span v-text="$t('term.version')" />
                </th>
                <td>
                  <span v-text="song.version" />
                </td>
              </tr>
            </tbody>
          </v-simple-table>
        </v-col>
      </v-row>

      <h2 class="my-6">
        <span v-text="$t('page.songs.sheetData')" />
      </h2>

      <v-row>
        <v-col cols="auto">
          <v-simple-table dense class="text-center overflow-x-auto">
            <thead>
              <th class="px-2">
                <span v-text="$t('term.type')" />
              </th>
              <th class="px-2">
                <span v-text="$t('term.difficulty')" />
              </th>
              <th class="px-2">
                <span v-text="$t('term.level')" />
              </th>
              <th class="px-2">
                <span v-text="$t('term.internalLevel')" />
              </th>
              <th
                v-for="(header, j) in extraSheetHeaders"
                :key="j"
                class="px-2"
              >
                <span v-text="header.title" />
              </th>
              <th class="px-2">
                <span v-text="$t('term.noteDesigner')" />
              </th>
            </thead>
            <tbody>
              <tr
                v-for="(sheet, i) in song.sheets"
                :key="i"
              >
                <td>
                  <span v-text="getTypeAbbr(sheet.type)" />
                </td>
                <td>
                  <v-btn
                    text
                    rounded
                    class="font-weight-bold text-none"
                    :style="{ 'color': getDifficultyColor(sheet.difficulty) }"
                    @click="viewSheet(sheet)"
                  >
                    <span v-text="getDifficultyName(sheet.difficulty)" />
                  </v-btn>
                </td>
                <td>
                  <span v-text="sheet.level" />
                </td>
                <td>
                  <span v-text="sheet.internalLevel" />
                </td>
                <td
                  v-for="(header, j) in extraSheetHeaders"
                  :key="j"
                >
                  <span v-text="header.get(sheet)" />
                  <v-tooltip
                    v-if="header.key === 'total' && !validateNoteCounts(sheet, gameCode)"
                    top
                  >
                    <template #activator="{ on }">
                      <span v-on="on">
                        <v-icon>mdi-alert-outline</v-icon>
                      </span>
                    </template>
                    <span v-text="$t('description.invalidNoteCounts')" />
                  </v-tooltip>
                </td>
                <td>
                  <span v-text="sheet.noteDesigner" />
                </td>
              </tr>
            </tbody>
          </v-simple-table>
        </v-col>
      </v-row>
    </template>
  </v-container>
</template>
