// src/components/SheetFilter.tsx
"use client";

import { useMemo, useState } from "react";
import { useTranslations } from "next-intl";
import { useSheetBrowserContext } from "@/contexts/SheetBrowserContext";
import { VirtualCombobox } from "@/components/VirtualCombobox";
import { MultiSelect } from "@/components/MultiSelect";
import { SuperFilterDialog } from "@/components/dialogs/SuperFilterDialog";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import type { FilterOption } from "@/types";

function options<T>(entries: FilterOption<T>[] | null) {
  return (entries ?? []).filter(
    (entry): entry is { $type: "option"; text: string; value: T } =>
      entry.$type === "option",
  );
}

export function SheetFilter() {
  const t = useTranslations();
  const { filters, setFilters, filterOptions } = useSheetBrowserContext();
  const [superOpen, setSuperOpen] = useState(false);
  const levelOptions = filters.useInternalLevel
    ? filterOptions.internalLevels
    : filterOptions.levels;
  const update = <K extends keyof typeof filters>(
    key: K,
    value: (typeof filters)[K],
  ) => setFilters((current) => ({ ...current, [key]: value }));
  const setSynced = (
    key: "minLevelValue" | "maxLevelValue" | "minBPM" | "maxBPM",
    value: string,
  ) =>
    setFilters((current) => {
      const numeric = value === "" ? null : Number(value);
      if (
        current.syncLevelValue &&
        (key === "minLevelValue" || key === "maxLevelValue")
      )
        return { ...current, minLevelValue: numeric, maxLevelValue: numeric };
      if (current.syncBPM && (key === "minBPM" || key === "maxBPM"))
        return { ...current, minBPM: numeric, maxBPM: numeric };
      return { ...current, [key]: numeric };
    });
  const multi = (
    key: "categories" | "versions" | "types" | "difficulties" | "noteDesigners",
    entries: FilterOption<string>[] | null,
  ) => (
    <MultiSelect
      options={options(entries).map((entry) => ({
        value: String(entry.value),
        text: entry.text,
      }))}
      value={filters[key]}
      onChange={(value) => update(key, value)}
      placeholder={t("ui.all")}
    />
  );
  const titleItems = useMemo(
    () => filterOptions.titles ?? [],
    [filterOptions.titles],
  );
  const artistItems = useMemo(
    () => filterOptions.artists ?? [],
    [filterOptions.artists],
  );
  const noteDesignerItems = useMemo(
    () =>
      options(filterOptions.noteDesigners).map((entry) => String(entry.value)),
    [filterOptions.noteDesigners],
  );
  return (
    <div className="grid gap-4 md:grid-cols-2">
      <div>
        <Label>{t("term.category")}</Label>
        {multi("categories", filterOptions.categories)}
      </div>
      <div>
        <Label>{t("term.title")}</Label>
        <div className="flex gap-2">
          <VirtualCombobox
            items={titleItems}
            value={filters.title}
            onChange={(value) => update("title", value as string | null)}
          />
          <Button
            variant={filters.matchExactTitle ? "default" : "outline"}
            size="icon"
            title={t("sfc.SheetFilter.exactMatch")}
            onClick={() =>
              update("matchExactTitle", filters.matchExactTitle ? null : true)
            }
          >
            ≡
          </Button>
        </div>
      </div>
      <div>
        <Label>{t("term.difficulty")}</Label>
        {multi("difficulties", [
          ...(filterOptions.difficulties ?? []),
          ...(filterOptions.extraDifficulties?.length
            ? [
                { $type: "divider", divider: true } as FilterOption<string>,
                ...filterOptions.extraDifficulties,
              ]
            : []),
        ])}
      </div>
      <div>
        <Label>
          {filters.useInternalLevel
            ? t("term.minInternalLevel")
            : t("term.minLevel")}{" "}
          /{" "}
          {filters.useInternalLevel
            ? t("term.maxInternalLevel")
            : t("term.maxLevel")}
        </Label>
        <div className="flex gap-2">
          <Select
            value={
              filters.minLevelValue == null ? "" : String(filters.minLevelValue)
            }
            onChange={(event) => setSynced("minLevelValue", event.target.value)}
            className="w-full"
          >
            <option value="">—</option>
            {options(levelOptions).map((entry) => (
              <option key={String(entry.value)} value={String(entry.value)}>
                {entry.text}
              </option>
            ))}
          </Select>
          <Button
            variant={filters.syncLevelValue ? "default" : "outline"}
            size="icon"
            onClick={() =>
              setFilters((current) => {
                const next = !current.syncLevelValue;
                const value = current.minLevelValue ?? current.maxLevelValue;
                return {
                  ...current,
                  syncLevelValue: next ? true : null,
                  minLevelValue: next ? value : current.minLevelValue,
                  maxLevelValue: next ? value : current.maxLevelValue,
                };
              })
            }
          >
            ↔
          </Button>
          <Select
            value={
              filters.maxLevelValue == null ? "" : String(filters.maxLevelValue)
            }
            onChange={(event) => setSynced("maxLevelValue", event.target.value)}
            className="w-full"
          >
            <option value="">—</option>
            {options(levelOptions).map((entry) => (
              <option key={String(entry.value)} value={String(entry.value)}>
                {entry.text}
              </option>
            ))}
          </Select>
          <Button
            variant={filters.useInternalLevel ? "default" : "outline"}
            size="icon"
            title={t("sfc.SheetFilter.useInternalLevel")}
            onClick={() =>
              update("useInternalLevel", filters.useInternalLevel ? null : true)
            }
          >
            CC
          </Button>
        </div>
      </div>
      <div>
        <Label>{t("term.version")}</Label>
        {multi("versions", filterOptions.versions)}
      </div>
      <div>
        <Label>{t("term.type")}</Label>
        {multi("types", filterOptions.types)}
      </div>
      <div>
        <Label>{t("term.artist")}</Label>
        <div className="flex gap-2">
          <VirtualCombobox
            items={artistItems}
            value={filters.artist}
            onChange={(value) => update("artist", value as string | null)}
          />
          <Button
            variant={filters.matchExactArtist ? "default" : "outline"}
            size="icon"
            title={t("sfc.SheetFilter.exactMatch")}
            onClick={() =>
              update("matchExactArtist", filters.matchExactArtist ? null : true)
            }
          >
            ≡
          </Button>
        </div>
      </div>
      <div>
        <Label>{t("term.noteDesigner")}</Label>
        <VirtualCombobox
          items={noteDesignerItems}
          multiple
          value={filters.noteDesigners}
          onChange={(value) =>
            update("noteDesigners", (value as string[]) ?? [])
          }
        />
      </div>
      <div>
        <Label>{t("term.region")}</Label>
        <div className="flex gap-2">
          <Select
            value={filters.region ?? ""}
            onChange={(event) => update("region", event.target.value || null)}
            className="w-full"
          >
            <option value="">{t("ui.all")}</option>
            {options(filterOptions.regions).map((entry) => (
              <option key={entry.value} value={entry.value}>
                {entry.text}
              </option>
            ))}
          </Select>
          <Button
            variant={filters.useRegionOverride ? "default" : "outline"}
            size="icon"
            disabled={!filters.region || filters.region.startsWith("!")}
            onClick={() =>
              update(
                "useRegionOverride",
                filters.useRegionOverride ? null : true,
              )
            }
          >
            ↻
          </Button>
        </div>
      </div>
      <div>
        <Label>
          {t("term.minBPM")} / {t("term.maxBPM")}
        </Label>
        <div className="flex gap-2">
          <Input
            type="number"
            min={0}
            value={filters.minBPM ?? ""}
            onChange={(event) => setSynced("minBPM", event.target.value)}
            placeholder={String(filterOptions.bpms?.at(0) ?? 0)}
          />
          <Button
            variant={filters.syncBPM ? "default" : "outline"}
            size="icon"
            onClick={() =>
              setFilters((current) => {
                const next = !current.syncBPM;
                const value = current.maxBPM ?? current.minBPM;
                return {
                  ...current,
                  syncBPM: next ? true : null,
                  minBPM: next ? value : current.minBPM,
                  maxBPM: next ? value : current.maxBPM,
                };
              })
            }
          >
            ↔
          </Button>
          <Input
            type="number"
            min={0}
            value={filters.maxBPM ?? ""}
            onChange={(event) => setSynced("maxBPM", event.target.value)}
            placeholder={String(filterOptions.bpms?.at(-1) ?? 999)}
          />
        </div>
      </div>
      {filters.superFilter !== null && (
        <div className="md:col-span-2">
          <Label>{t("term.superFilter")}</Label>
          <Button
            variant="outline"
            className="h-auto min-h-20 w-full justify-start whitespace-pre-wrap text-left font-mono"
            onClick={() => setSuperOpen(true)}
          >
            {filters.superFilter || t("description.superFilterPlaceholder")}
          </Button>
          <SuperFilterDialog
            open={superOpen}
            onOpenChange={setSuperOpen}
            value={filters.superFilter}
            onCommit={(value) => update("superFilter", value)}
          />
        </div>
      )}
    </div>
  );
}

// components/SheetFilter.vue
<script setup lang="ts">
import { ref, computed, watch, inject, Ref } from '@nuxtjs/composition-api';
import useSheetDialog from '~/composables/useSheetDialog';
import SuperFilterDialog from '~/components/dialogs/SuperFilterDialog.vue';
import { parseSuperFilter, makeShyCatSheet } from '~/utils';
import type { Filters, FilterOptions } from '~/types';

const filters: Ref<Filters> = inject('filters')!;
const filterOptions: Ref<FilterOptions> = inject('filterOptions')!;

const { viewSheet } = useSheetDialog();

const isSuperFilterDialogOpened = ref(false);

const currentLevelFilterOptions = computed(() => (
  filters.value.useInternalLevel
    ? filterOptions.value.internalLevels
    : filterOptions.value.levels
));

function validateSuperFilter(superFilterText: string): boolean | string {
  try {
    const superFilter = parseSuperFilter(superFilterText);

    if (typeof superFilter !== 'function') {
      if (typeof superFilter !== 'undefined') {
        viewSheet(makeShyCatSheet(superFilter, 'INVALID SUPER FILTER'));
      }

      throw new TypeError('You should return a predicate function.');
    }

    return true;
  } catch (err) {
    return String(err);
  }
}

// Sync Level Filter
watch(() => filters.value.minLevelValue, () => {
  if (filters.value.syncLevelValue) {
    filters.value.maxLevelValue = filters.value.minLevelValue;
  }
});
watch(() => filters.value.maxLevelValue, () => {
  if (filters.value.syncLevelValue) {
    filters.value.minLevelValue = filters.value.maxLevelValue;
  }
});
watch(() => filters.value.syncLevelValue, () => {
  if (filters.value.syncLevelValue) {
    const levelValue = filters.value.minLevelValue ?? filters.value.maxLevelValue;
    filters.value.minLevelValue = levelValue;
    filters.value.maxLevelValue = levelValue;
  }
}, { immediate: true });

// Sync BPM Filter
watch(() => filters.value.minBPM, () => {
  if (filters.value.syncBPM) {
    filters.value.maxBPM = filters.value.minBPM;
  }
});
watch(() => filters.value.maxBPM, () => {
  if (filters.value.syncBPM) {
    filters.value.minBPM = filters.value.maxBPM;
  }
});
watch(() => filters.value.syncBPM, () => {
  if (filters.value.syncBPM) {
    const bpm = filters.value.maxBPM ?? filters.value.minBPM;
    filters.value.minBPM = bpm;
    filters.value.maxBPM = bpm;
  }
}, { immediate: true });
</script>

<template>
  <div>
    <v-row>
      <!-- Category -->
      <v-col
        v-if="filterOptions.categories != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-select
          v-model="filters.categories"
          :items="filterOptions.categories"
          prepend-icon="mdi-folder-multiple-outline"
          :label="$t('term.category')"
          :placeholder="$t('ui.all')"
          persistent-placeholder
          multiple
          chips
          deletable-chips
          clearable
        />
      </v-col>
      <!-- Title -->
      <v-col
        v-if="filterOptions.titles != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-combobox
            v-model="filters.title"
            :items="filterOptions.titles"
            prepend-icon="mdi-alphabetical-variant"
            :label="$t('term.title')"
            :placeholder="$t('ui.all')"
            persistent-placeholder
            clearable
          />
        </div>
        <div class="d-flex flex-grow-0 align-center pl-4 align-self-stretch">
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                :color="!filters.matchExactTitle ? null : 'accent'"
                @click="filters.matchExactTitle = !filters.matchExactTitle || null"
                v-on="on"
              >
                <v-icon size="2.0em">
                  mdi-format-letter-matches
                </v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetFilter.exactMatch')" />
          </v-tooltip>
        </div>
      </v-col>
      <!-- Difficulty -->
      <v-col
        v-if="filterOptions.difficulties != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-select
          v-model="filters.difficulties"
          :items="[
            ...filterOptions.difficulties,
            ...(filterOptions.extraDifficulties != null ? [
              { divider: true },
              ...filterOptions.extraDifficulties,
            ] : []),
          ]"
          prepend-icon="mdi-skull-outline"
          :label="$t('term.difficulty')"
          :placeholder="$t('ui.all')"
          persistent-placeholder
          multiple
          chips
          deletable-chips
          clearable
        />
      </v-col>
      <!-- Level / Internal Level -->
      <v-col
        v-if="filterOptions.levels != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-select
            v-model="filters.minLevelValue"
            :items="currentLevelFilterOptions"
            prepend-icon="mdi-numeric-9-plus-box-multiple-outline"
            :label="filters.useInternalLevel ? $t('term.minInternalLevel') : $t('term.minLevel')"
            :placeholder="currentLevelFilterOptions?.at(0)?.text ?? '?'"
            persistent-placeholder
            clearable
          />
        </div>
        <div class="d-flex flex-grow-0 align-center px-2 align-self-stretch">
          <v-btn
            icon
            :color="!filters.syncLevelValue ? null : 'accent'"
            @click="filters.syncLevelValue = !filters.syncLevelValue || null"
          >
            <v-icon size="2.0em">
              {{ !filters.syncLevelValue ? 'mdi-link-off' : 'mdi-link' }}
            </v-icon>
          </v-btn>
        </div>
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-select
            v-model="filters.maxLevelValue"
            :items="currentLevelFilterOptions"
            :label="filters.useInternalLevel ? $t('term.maxInternalLevel') : $t('term.maxLevel')"
            :placeholder="currentLevelFilterOptions?.at(-1)?.text ?? '?'"
            persistent-placeholder
            clearable
          />
        </div>
        <div
          v-if="filterOptions.internalLevels != null && filterOptions.internalLevels.length !== 0"
          class="d-flex flex-grow-0 align-center pl-4 align-self-stretch"
        >
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                :color="!filters.useInternalLevel ? null : 'accent'"
                @click="filters.useInternalLevel = !filters.useInternalLevel || null"
                v-on="on"
              >
                <v-icon size="2.4em">
                  <!-- eslint-disable-next-line max-len -->
                  {{ !filters.useInternalLevel ? 'mdi-closed-caption-outline' : 'mdi-closed-caption' }}
                </v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetFilter.useInternalLevel')" />
          </v-tooltip>
        </div>
      </v-col>
      <!-- Version -->
      <v-col
        v-if="filterOptions.versions != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-select
          v-model="filters.versions"
          :items="filterOptions.versions"
          prepend-icon="mdi-star-outline"
          :label="$t('term.version')"
          :placeholder="$t('ui.all')"
          persistent-placeholder
          multiple
          chips
          deletable-chips
          clearable
        />
      </v-col>
      <!-- Type -->
      <v-col
        v-if="filterOptions.types != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-select
          v-model="filters.types"
          :items="filterOptions.types"
          prepend-icon="mdi-assistant"
          :label="$t('term.type')"
          :placeholder="$t('ui.all')"
          persistent-placeholder
          multiple
          chips
          deletable-chips
          clearable
        />
      </v-col>
      <!-- Artist -->
      <v-col
        v-if="filterOptions.artists != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-combobox
            v-model="filters.artist"
            :items="filterOptions.artists"
            prepend-icon="mdi-account-music-outline"
            :label="$t('term.artist')"
            :placeholder="$t('ui.all')"
            persistent-placeholder
            clearable
          />
        </div>
        <div class="d-flex flex-grow-0 align-center pl-4 align-self-stretch">
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                :color="!filters.matchExactArtist ? null : 'accent'"
                @click="filters.matchExactArtist = !filters.matchExactArtist || null"
                v-on="on"
              >
                <v-icon size="2.0em">
                  mdi-format-letter-matches
                </v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetFilter.exactMatch')" />
          </v-tooltip>
        </div>
      </v-col>
      <!-- Note Designer -->
      <v-col
        v-if="filterOptions.noteDesigners != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-select
          v-model="filters.noteDesigners"
          :items="filterOptions.noteDesigners"
          prepend-icon="mdi-account-edit-outline"
          :label="$t('term.noteDesigner')"
          :placeholder="$t('ui.all')"
          persistent-placeholder
          multiple
          chips
          deletable-chips
          clearable
        />
      </v-col>
      <!-- Region -->
      <v-col
        v-if="filterOptions.regions != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-select
            v-model="filters.region"
            :items="filterOptions.regions"
            prepend-icon="mdi-map-search"
            :label="$t('term.region')"
            :placeholder="$t('ui.all')"
            persistent-placeholder
            clearable
          />
        </div>
        <div class="d-flex flex-grow-0 align-center pl-4 align-self-stretch">
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                :color="!filters.useRegionOverride ? null : 'accent'"
                :disabled="filters.region == null || filters.region.startsWith('!')"
                @click="filters.useRegionOverride = !filters.useRegionOverride || null"
                v-on="on"
              >
                <v-icon size="2.0em">
                  {{ !filters.useRegionOverride ? 'mdi-file-replace-outline' : 'mdi-file-replace' }}
                </v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetFilter.useRegionOverride')" />
          </v-tooltip>
        </div>
      </v-col>
      <!-- BPM -->
      <v-col
        v-if="filterOptions.bpms != null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-text-field
            v-model.number="filters.minBPM"
            type="number"
            :min="0"
            prepend-icon="mdi-metronome"
            :label="$t('term.minBPM')"
            :placeholder="String(filterOptions.bpms.at(0) ?? 0)"
            persistent-placeholder
            clearable
          />
        </div>
        <div class="d-flex flex-grow-0 align-center px-2 align-self-stretch">
          <v-btn
            icon
            :color="!filters.syncBPM ? null : 'accent'"
            @click="filters.syncBPM = !filters.syncBPM || null"
          >
            <v-icon size="2.0em">
              {{ !filters.syncBPM ? 'mdi-link-off' : 'mdi-link' }}
            </v-icon>
          </v-btn>
        </div>
        <div class="d-flex flex-grow-1 align-end" style="min-width: 0;">
          <v-text-field
            v-model.number="filters.maxBPM"
            type="number"
            :min="0"
            :label="$t('term.maxBPM')"
            :placeholder="String(filterOptions.bpms.at(-1) ?? 999)"
            persistent-placeholder
            clearable
          />
        </div>
      </v-col>
      <!-- Super Filter -->
      <v-col
        v-if="filters.superFilter !== null"
        cols="12"
        md="6"
        class="d-flex align-end"
      >
        <v-textarea
          v-model="filters.superFilter"
          rows="3"
          :rules="[validateSuperFilter]"
          prepend-icon="mdi-code-braces-box"
          :label="`${$t('term.superFilter')} (JavaScript)`"
          :placeholder="$t('description.superFilterPlaceholder')"
          :hint="$t('description.superFilterHint')"
          persistent-placeholder
          outlined
          auto-grow
          readonly
          class="SuperFilter"
          style="font-family: Consolas, monospace;"
          @click="isSuperFilterDialogOpened = true;"
        />
        <SuperFilterDialog
          v-model="isSuperFilterDialogOpened"
          :super-filter-text.sync="filters.superFilter"
        />
      </v-col>
    </v-row>
  </div>
</template>

<style lang="scss" scoped>
::v-deep {
  .SuperFilter {
    textarea {
      cursor: pointer;
      caret-color: transparent;
    }
  }
}
</style>
