// pages/_gameCode/gallery.vue
<script setup lang="ts">
/* eslint-disable import/first, import/no-duplicates */
import { ref, computed, watch, onMounted, useRoute, useRouter, useMeta as useHead, Ref } from '@nuxtjs/composition-api';
import { until } from '@vueuse/core';
import YAML from 'yaml';
import { useDataStore } from '~/stores/data';
import useI18n from '~/composables/useI18n';
import useDarkMode from '~/composables/useDarkMode';
import useGameInfo from '~/composables/useGameInfo';
import useSheetDialog from '~/composables/useSheetDialog';
import useGlobalComponents from '~/composables/useGlobalComponents';
import LoadingOverlay from '~/components/LoadingOverlay.vue';
import SheetTile from '~/components/SheetTile.vue';
import LoadingStatus from '~/enums/LoadingStatus';
import { buildGallery, isValidUrl, selectFiles } from '~/utils';
import type { Gallery, GalleryList } from '~/types';

const i18n = useI18n();
const route = useRoute();
const router = useRouter();
const dataStore = useDataStore();
const { isDarkMode } = useDarkMode();
const { dataSourceUrl } = useGameInfo();
const { viewSheet } = useSheetDialog();
// re-export the shadowed <i18n /> component as <i18n-t />
const { i18n: I18nT } = useGlobalComponents();

const galleryProviders = computed(() => [
  { type: 'default', title: 'Load from default' },
  { type: 'url', title: 'Load from URL' },
  { type: 'file', title: 'Load from File' },
  { type: 'example', title: 'View an Example!' },
]);

const currentGalleryProvider: Ref<string> = ref('');
const externalGalleryUrl: Ref<string> = ref('');
const currentLoadingStatus: Ref<LoadingStatus> = ref(LoadingStatus.PENDING);

const currentGallery: Ref<Gallery> = ref([]);
const currentLists = computed(
  () => currentGallery.value.filter((list) => !list.isHidden || isDarkMode.value),
);
const currentList: Ref<GalleryList | null> = ref(null);

async function loadDefaultGallery() {
  currentLoadingStatus.value = LoadingStatus.LOADING;
  try {
    const response = await fetch(`${dataSourceUrl.value}/gallery.yaml`);
    const data = YAML.parse(await response.text());

    await until(() => dataStore.currentLoadingStatus).toBe(LoadingStatus.LOADED);

    currentGalleryProvider.value = 'default';
    currentGallery.value = buildGallery(data, dataStore.currentData.sheets);
  } catch (err) {
    currentLoadingStatus.value = LoadingStatus.ERROR;

    // eslint-disable-next-line no-console
    console.info('The gallery is currently unavailable.');

    return false;
  }
  currentLoadingStatus.value = LoadingStatus.LOADED;

  return true;
}

async function loadExternalGalleryFromUrl(galleryUrl: string) {
  // eslint-disable-next-line no-alert
  const confirm = window.confirm(
    i18n.t('page.gallery.loadExternalGalleryConfirmation', {
      srcType: i18n.t('page.gallery.thisUrl'),
      src: galleryUrl,
    }) as string,
  );

  if (!confirm) return false;

  if (!isValidUrl(galleryUrl)) {
    // eslint-disable-next-line no-alert
    window.alert('Please enter a valid URL.');

    return false;
  }

  currentLoadingStatus.value = LoadingStatus.LOADING;
  try {
    const response = await fetch(galleryUrl);
    const data = YAML.parse(await response.text());

    await until(() => dataStore.currentLoadingStatus).toBe(LoadingStatus.LOADED);

    externalGalleryUrl.value = galleryUrl;
    currentGalleryProvider.value = 'url';
    currentGallery.value = buildGallery(data, dataStore.currentData.sheets);
  } catch (err) {
    currentLoadingStatus.value = LoadingStatus.ERROR;

    // eslint-disable-next-line no-alert
    window.alert([
      'Encounter an error while reading from url:',
      err,
    ].join('\n'));
    // eslint-disable-next-line no-console
    console.error(err);

    return false;
  }
  currentLoadingStatus.value = LoadingStatus.LOADED;

  return true;
}

async function loadExternalGalleryFromFile(galleryFile: File) {
  // eslint-disable-next-line no-alert
  const confirm = window.confirm(
    i18n.t('page.gallery.loadExternalGalleryConfirmation', {
      srcType: i18n.t('page.gallery.thisFile'),
      src: galleryFile.name,
    }) as string,
  );

  if (!confirm) return false;

  currentLoadingStatus.value = LoadingStatus.LOADING;
  try {
    const data = YAML.parse(await galleryFile.text());

    await until(() => dataStore.currentLoadingStatus).toBe(LoadingStatus.LOADED);

    currentGalleryProvider.value = 'file';
    currentGallery.value = buildGallery(data, dataStore.currentData.sheets);
  } catch (err) {
    currentLoadingStatus.value = LoadingStatus.ERROR;

    // eslint-disable-next-line no-alert
    window.alert([
      'Encounter an error while reading from file:',
      err,
    ].join('\n'));
    // eslint-disable-next-line no-console
    console.error(err);

    return false;
  }
  currentLoadingStatus.value = LoadingStatus.LOADED;

  return true;
}

async function changeGalleryProvider(providerType: string) {
  if (providerType === 'default') {
    await loadDefaultGallery();
  } else if (providerType === 'url') {
    // eslint-disable-next-line no-alert
    const galleryUrl = window.prompt('Please enter a gallery data URL:');

    if (galleryUrl === null) return;

    await loadExternalGalleryFromUrl(galleryUrl);
  } else if (providerType === 'file') {
    const files = await selectFiles({ accept: '.yaml', multiple: false });

    if (files === null || files.length === 0) return;

    const galleryFile = files[0];

    await loadExternalGalleryFromFile(galleryFile);
  } else if (providerType === 'example') {
    window.open('/maimai/gallery/?url=https%3A%2F%2Fgist.githubusercontent.com%2Fzetaraku%2Fc8a28b5bbd17cd421278ec45f4e4e953%2Fraw%2F');
  }
}

useHead(() => ({
  title: (
    currentList.value !== null
      ? `${currentList.value.title} | ${i18n.t('page-title.gallery')}`
      : i18n.t('page-title.gallery') as string
  ),
}));

onMounted(async () => {
  if (route.value.query.url !== undefined) {
    const externalGalleryLoaded = await loadExternalGalleryFromUrl(route.value.query.url as string);

    if (!externalGalleryLoaded) {
      await loadDefaultGallery();
      return;
    }
  } else {
    await loadDefaultGallery();
  }

  if (route.value.query.id !== undefined) {
    currentList.value = currentLists.value
      .find((list) => list.id === route.value.query.id) ?? currentList.value;
  }
  if (route.value.query.title !== undefined) {
    currentList.value = currentLists.value
      .find((list) => list.title === route.value.query.title) ?? currentList.value;
  }
});

watch(currentLists, () => {
  currentList.value = currentLists.value[0] ?? null;
});
watch(currentList, () => {
  if (currentList.value === null) return;

  const listKey = (() => {
    if (currentList.value.id != null) return { id: currentList.value.id };
    if (currentList.value.title != null) return { title: currentList.value.title };
    return {};
  })();

  router.push({
    query: {
      ...listKey,
      url: currentGalleryProvider.value === 'url' ? externalGalleryUrl.value : undefined,
    },
  });
});
</script>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api';

export default defineComponent({
  name: 'GalleryPage',
  head: {},
});
</script>

<template>
  <v-container class="text-center pa-4 pa-sm-8">
    <LoadingOverlay
      v-if="
        currentLoadingStatus === LoadingStatus.LOADING
          && dataStore.currentLoadingStatus !== LoadingStatus.LOADING
      "
    />

    <v-row class="mb-10">
      <v-col>
        <v-select
          v-model="currentList"
          :items="currentLists"
          :label="$t('page.gallery.selectList')"
          item-text="title"
          return-object
          hide-details
          outlined
        />
      </v-col>
      <v-col cols="auto" class="d-flex align-center">
        <v-menu offset-y :nudge-bottom="8">
          <template #activator="{ on }">
            <v-btn
              outlined
              color="success"
              class="px-4 py-6"
              v-on="on"
            >
              <v-icon>mdi-list-box-outline</v-icon>
            </v-btn>
          </template>
          <v-list>
            <v-list-item
              v-for="(provider, i) in galleryProviders"
              :key="i"
              @click="changeGalleryProvider(provider.type);"
            >
              <v-list-item-title>
                {{ provider.title }}
              </v-list-item-title>
            </v-list-item>
          </v-list>
        </v-menu>
      </v-col>
    </v-row>

    <v-alert
      v-if="currentGalleryProvider === 'url'"
      type="info"
      class="mb-6"
      outlined
    >
      <i18n-t path="page.gallery.externalGalleryDisclaimer">
        <template #source>
          👉 <a :href="externalGalleryUrl" target="_blank">{{ $t('page.gallery.thisUrl') }}</a>
        </template>
        <template #br>
          <br>
        </template>
      </i18n-t>
    </v-alert>
    <v-alert
      v-if="currentGalleryProvider === 'file'"
      type="info"
      class="mb-6"
      outlined
    >
      <i18n-t path="page.gallery.externalGalleryDisclaimer">
        <template #source>
          <b>{{ $t('page.gallery.yourLocalFile') }}</b>
        </template>
        <template #br>
          <br>
        </template>
      </i18n-t>
    </v-alert>

    <!-- Current List -->
    <template v-if="currentList !== null">
      <!-- List title -->
      <h1
        class="text-pre-wrap mb-8"
        v-text="currentList.title"
      />

      <!-- List description -->
      <p
        v-if="currentList.description != null"
        class="text-pre-wrap mb-10"
        v-text="currentList.description"
      />

      <!-- Sections -->
      <div
        v-for="(section, i) in currentList.sections"
        :key="i"
        class="mb-6"
        :class="{ 'yellow--text': currentList.isHidden }"
      >
        <!-- Section title -->
        <h2
          v-if="section.title != null"
          class="text-pre-wrap mb-4"
          v-text="section.title"
        />

        <!-- Section description -->
        <p
          v-if="section.description != null"
          class="text-pre-wrap"
          v-text="section.description"
        />

        <!-- Sheets -->
        <div
          v-if="section.sheets != null"
          class="d-flex flex-wrap justify-center"
          style="gap: 8px;"
        >
          <!-- Sheet tile -->
          <SheetTile
            v-for="(sheet, j) in section.sheets"
            :key="j"
            :sheet="sheet"
            @click="viewSheet(sheet)"
          >
            <!-- Sheet description -->
            <template #description>
              <span
                v-if="section.sheetDescriptions != null"
                v-text="section.sheetDescriptions[j]"
              />
            </template>
          </SheetTile>
        </div>
      </div>
    </template>
  </v-container>
</template>

<style lang="scss" scoped>
::v-deep {
  .v-alert__icon {
    margin: auto 16px auto 0;
  }
}
</style>

// src/app/[gameCode]/gallery/page.tsx
"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useTheme } from "next-themes";
import { useTranslations } from "next-intl";
import YAML from "yaml";
import { useGameContext } from "@/contexts/GameContext";
import { useCurrentData, useGameDataQuery } from "@/hooks/useGameDataQuery";
import { buildGallery, isValidUrl, selectFiles } from "@/lib/utils";
import { SheetTile } from "@/components/SheetTile";
import { LoadingOverlay } from "@/components/LoadingOverlay";
import { Select } from "@/components/ui/select";
import { Alert } from "@/components/ui/alert";
import type { Gallery, RawGallery } from "@/types";

function GalleryContent() {
  const t = useTranslations();
  const params = useSearchParams();
  const router = useRouter();
  const pathname = usePathname();
  const { resolvedTheme } = useTheme();
  const { dataSourceUrl } = useGameContext();
  const data = useCurrentData();
  const query = useGameDataQuery();
  const [gallery, setGallery] = useState<Gallery>([]);
  const [provider, setProvider] = useState("");
  const [externalUrl, setExternalUrl] = useState("");
  const [currentListKey, setCurrentListKey] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const visibleLists = useMemo(
    () => gallery.filter((list) => !list.isHidden || resolvedTheme === "dark"),
    [gallery, resolvedTheme],
  );
  const currentList =
    visibleLists.find((list) => (list.id ?? list.title) === currentListKey) ??
    visibleLists[0];
  const load = async (source: string, url?: string, file?: File) => {
    setLoading(true);
    setError("");
    try {
      const raw = file
        ? await file.text()
        : await (await fetch(url ?? `${dataSourceUrl}/gallery.yaml`)).text();
      const built = buildGallery(YAML.parse(raw) as RawGallery, data.sheets);
      setGallery(built);
      setProvider(source);
      if (url) setExternalUrl(url);
      setCurrentListKey(
        built.find(
          (list) =>
            list.id === params.get("id") || list.title === params.get("title"),
        )?.id ??
          built.find(
            (list) =>
              list.id === params.get("id") ||
              list.title === params.get("title"),
          )?.title ??
          built[0]?.id ??
          built[0]?.title ??
          "",
      );
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    if (query.isSuccess) {
      const external = params.get("url");
      void load(external ? "url" : "default", external ?? undefined);
    } // the loaded data is the dependency that makes local gallery resolution safe
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query.isSuccess, data.sheets, dataSourceUrl]);
  useEffect(() => {
    if (!currentList) return;
    const next = new URLSearchParams();
    if (currentList.id) next.set("id", currentList.id);
    else next.set("title", currentList.title);
    if (provider === "url" && externalUrl) next.set("url", externalUrl);
    router.push(`${pathname}?${next.toString()}`);
  }, [currentList, externalUrl, pathname, provider, router]);
  const changeProvider = async (value: string) => {
    if (value === "default") {
      await load("default");
      return;
    }
    if (value === "url") {
      const url = window.prompt("Please enter a gallery data URL:");
      if (!url) return;
      if (!isValidUrl(url)) {
        window.alert("Please enter a valid URL.");
        return;
      }
      if (
        !window.confirm(
          t("page.gallery.loadExternalGalleryConfirmation", {
            srcType: t("page.gallery.thisUrl"),
            src: url,
          }),
        )
      )
        return;
      await load("url", url);
    }
    if (value === "file") {
      const files = await selectFiles({ accept: ".yaml", multiple: false });
      if (
        files?.[0] &&
        window.confirm(
          t("page.gallery.loadExternalGalleryConfirmation", {
            srcType: t("page.gallery.thisFile"),
            src: files[0].name,
          }),
        )
      )
        await load("file", undefined, files[0]);
    }
    if (value === "example")
      window.open(
        "/maimai/gallery/?url=https%3A%2F%2Fgist.githubusercontent.com%2Fzetaraku%2Fc8a28b5bbd17cd421278ec45f4e4e953%2Fraw%2F",
        "_blank",
      );
  };
  return (
    <div className="mx-auto max-w-screen-xl px-4 py-6 text-center sm:px-8">
      {loading && <LoadingOverlay />}
      <div className="mb-8 flex gap-2">
        <Select
          value={currentList ? (currentList.id ?? currentList.title) : ""}
          onChange={(event) => setCurrentListKey(event.target.value)}
          className="flex-1 text-left"
        >
          <option value="">{t("page.gallery.selectList")}</option>
          {visibleLists.map((list) => (
            <option key={list.id ?? list.title} value={list.id ?? list.title}>
              {list.title}
            </option>
          ))}
        </Select>
        <Select
          aria-label="Gallery source"
          value=""
          onChange={(event) => {
            void changeProvider(event.target.value);
          }}
          className="w-12"
        >
          <option value="">☷</option>
          <option value="default">Default</option>
          <option value="url">URL</option>
          <option value="file">File</option>
          <option value="example">Example</option>
        </Select>
      </div>
      {error && (
        <Alert className="mb-6 border-red-500 text-left text-red-600">
          {error}
        </Alert>
      )}
      {provider === "url" && externalUrl && (
        <Alert className="mb-6 text-left whitespace-pre-line">
          {t("page.gallery.externalGalleryDisclaimer", {
            source: `👉 ${externalUrl}`,
            br: "\n",
          })}
        </Alert>
      )}
      {provider === "file" && (
        <Alert className="mb-6 text-left whitespace-pre-line">
          {t("page.gallery.externalGalleryDisclaimer", {
            source: t("page.gallery.yourLocalFile"),
            br: "\n",
          })}
        </Alert>
      )}
      {currentList ? (
        <>
          <h1 className="mb-8 whitespace-pre-wrap text-3xl font-semibold">
            {currentList.title}
          </h1>
          {currentList.description && (
            <p className="mb-10 whitespace-pre-wrap">
              {currentList.description}
            </p>
          )}
          {currentList.sections.map((section, index) => (
            <section key={`${section.title}-${index}`} className="mb-8">
              <h2 className="mb-3 whitespace-pre-wrap text-2xl font-semibold">
                {section.title}
              </h2>
              {section.description && (
                <p className="mb-4 whitespace-pre-wrap">
                  {section.description}
                </p>
              )}
              <div className="flex flex-wrap justify-center gap-2">
                {section.sheets?.map((sheet, sheetIndex) => (
                  <div key={`${sheet.sheetExpr ?? sheet.songNo}-${sheetIndex}`}>
                    <SheetTile sheet={sheet} />
                    <p className="max-w-32 whitespace-pre-wrap text-sm opacity-80">
                      {section.sheetDescriptions?.[sheetIndex]}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </>
      ) : (
        !query.isPending && <p className="py-10 opacity-70">No gallery data.</p>
      )}
    </div>
  );
}

export default function GalleryPage() {
  return (
    <Suspense fallback={<div className="p-10 text-center">Loading…</div>}>
      <GalleryContent />
    </Suspense>
  );
}
