// components/ModeSelector.vue
<script setup lang="ts">
import { ref, inject, Ref } from '@nuxtjs/composition-api';
import YAML from 'yaml';
import QueryString from 'query-string';
import copyToClipboard from 'copy-to-clipboard';
import { useDataStore } from '~/stores/data';
import useI18n from '~/composables/useI18n';
import useSelectedSheets from '~/composables/useSelectedSheets';
import MyListExportDialog from '~/components/dialogs/MyListExportDialog.vue';
import { saveFiltersAsQuery, selectFiles, makeDummySheet } from '~/utils';
import type { Filters } from '~/types';

const displayMode: Ref<string> = inject('displayMode')!;
const filterMode: Ref<string> = inject('filterMode')!;
const filters: Ref<Filters> = inject('filters')!;

const i18n = useI18n();
const dataStore = useDataStore();
const { selectedSheets } = useSelectedSheets();

const isMyListExportDialogOpened = ref(false);

function copyFilterLink() {
  const query = saveFiltersAsQuery(filters.value);

  if (Object.keys(query).length === 0) {
    // eslint-disable-next-line no-alert
    window.alert(i18n.t('sfc.ModeSelector.noFilterWarn'));
    return;
  }

  const url = QueryString.stringifyUrl({ url: window.location.href, query });
  copyToClipboard(url, { format: 'text/plain' });

  // eslint-disable-next-line no-alert
  window.alert(`${url}\n${i18n.t('description.copied')}`);
}
function toggleSuperFilter() {
  if (filters.value.superFilter === null) {
    filters.value.superFilter = '';
  } else {
    filters.value.superFilter = null;
  }
}
async function showMyListExportDialog() {
  if (selectedSheets.value.length === 0) {
    // eslint-disable-next-line no-alert
    window.alert(i18n.t('sfc.ModeSelector.myListEmptyWarn'));
    return;
  }

  isMyListExportDialogOpened.value = true;
}
async function importSelectedSheets() {
  const files = await selectFiles({ accept: '.yaml', multiple: false });

  if (files === null || files.length === 0) return;

  const sheetMap = new Map(dataStore.currentData.sheets.map((sheet) => [sheet.sheetExpr, sheet]));

  try {
    const file = files[0];
    const sheetExprs = [...new Set(YAML.parse(await file.text()))] as string[];

    const loadedSheets = sheetExprs.map(
      (sheetExpr) => sheetMap.get(sheetExpr) ?? makeDummySheet(sheetExpr),
    );
    selectedSheets.value = loadedSheets;

    // eslint-disable-next-line no-alert
    window.alert(i18n.t('sfc.ModeSelector.sheetsLoaded', { n: loadedSheets.length }));
  } catch (err) {
    // eslint-disable-next-line no-alert
    window.alert(`An error occurred while loading '${files[0].name}':\n\n${err}`);
  }
}
</script>

<template>
  <div>
    <v-row no-gutters>
      <v-col
        cols="12"
        sm="6"
        class="d-flex justify-center align-center"
      >
        <v-radio-group
          v-model="displayMode"
          row
        >
          <v-radio value="grid">
            <template #label>
              <span>
                <v-icon>mdi-view-grid-outline</v-icon>
                <span v-text="$t('sfc.ModeSelector.gridMode')" />
              </span>
            </template>
          </v-radio>
          <v-radio value="table">
            <template #label>
              <span>
                <v-icon>mdi-table</v-icon>
                <span v-text="$t('sfc.ModeSelector.tableMode')" />
              </span>
            </template>
          </v-radio>
          <v-radio value="chart">
            <template #label>
              <span>
                <v-icon>mdi-chart-bar</v-icon>
                <span v-text="$t('sfc.ModeSelector.chartMode')" />
              </span>
            </template>
          </v-radio>
        </v-radio-group>
      </v-col>

      <v-col
        cols="12"
        sm="6"
        class="d-flex justify-center align-center"
      >
        <v-radio-group
          v-model="filterMode"
          row
        >
          <v-radio value="filter">
            <template #label>
              <span>
                <v-icon>mdi-filter-menu-outline</v-icon>
                <span v-text="$t('sfc.ModeSelector.filterMode')" />
              </span>
            </template>
          </v-radio>
          <v-radio value="my-list">
            <template #label>
              <span>
                <v-icon>mdi-playlist-music</v-icon>
                <span v-text="$t('sfc.ModeSelector.myListMode')" />
                <v-badge
                  v-if="selectedSheets.length > 0"
                  inline
                  color="error"
                  style="font-weight: bold;"
                  :content="selectedSheets.length"
                />
              </span>
            </template>
          </v-radio>
        </v-radio-group>

        <template v-if="filterMode === 'filter'">
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                large
                color="green"
                @click="copyFilterLink"
                v-on="on"
              >
                <v-icon>mdi-link-box-variant</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.ModeSelector.copyFilterLink')" />
          </v-tooltip>
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                large
                color="grey darken-1"
                @click="toggleSuperFilter"
                v-on="on"
              >
                <v-icon>mdi-code-braces-box</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('term.superFilter')" />
          </v-tooltip>
        </template>
        <template v-if="filterMode === 'my-list'">
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                large
                color="cyan"
                @click="showMyListExportDialog"
                v-on="on"
              >
                <v-icon>mdi-download</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.ModeSelector.exportMyList')" />
          </v-tooltip>
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                icon
                large
                color="red"
                @click="importSelectedSheets"
                v-on="on"
              >
                <v-icon>mdi-upload</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.ModeSelector.importMyList')" />
          </v-tooltip>
        </template>
      </v-col>
    </v-row>

    <MyListExportDialog v-model="isMyListExportDialogOpened" />
  </div>
</template>

// src/components/ModeSelector.tsx
'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';
import YAML from 'yaml';
import copyToClipboard from 'copy-to-clipboard';
import { useSheetBrowserContext } from '@/contexts/SheetBrowserContext';
import { useCurrentData } from '@/hooks/useGameDataQuery';
import { useSelectedSheets } from '@/hooks/useSelectedSheets';
import { makeDummySheet, saveFiltersAsQuery, selectFiles } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { MyListExportDialog } from '@/components/dialogs/MyListExportDialog';

export function ModeSelector() {
  const t = useTranslations(); const { displayMode, setDisplayMode, filterMode, setFilterMode, filters, setFilters } = useSheetBrowserContext(); const data = useCurrentData(); const { selectedSheets, setSelectedSheets } = useSelectedSheets(); const [exportOpen, setExportOpen] = useState(false);
  const copyFilterLink = () => { const query = saveFiltersAsQuery(filters); if (Object.keys(query).length === 0) { window.alert(t('sfc.ModeSelector.noFilterWarn')); return; } const params = new URLSearchParams(query); const url = `${window.location.pathname}?${params.toString().replaceAll('%7C', '|')}`; copyToClipboard(url); window.alert(`${url}\n${t('description.copied')}`); };
  const importSelectedSheets = async () => { const files = await selectFiles({ accept: '.yaml', multiple: false }); if (!files?.length) return; try { const expressions = [...new Set(YAML.parse(await files[0].text()) as string[])]; const map = new Map(data.sheets.map((sheet) => [sheet.sheetExpr, sheet])); const loaded = expressions.map((expr) => map.get(expr) ?? makeDummySheet(expr)); setSelectedSheets(loaded); window.alert(t('sfc.ModeSelector.sheetsLoaded', { n: loaded.length })); } catch (error) { window.alert(`An error occurred while loading '${files[0].name}':\n\n${error}`); } };
  return <div className="flex flex-wrap items-center justify-center gap-5 py-3"><div className="flex flex-wrap justify-center gap-1">{(['grid', 'table', 'chart'] as const).map((mode) => <Button key={mode} variant={displayMode === mode ? 'default' : 'outline'} size="sm" onClick={() => setDisplayMode(mode)}>{t(`sfc.ModeSelector.${mode}Mode`)}</Button>)}</div><div className="flex flex-wrap items-center justify-center gap-1"><Button variant={filterMode === 'filter' ? 'default' : 'outline'} size="sm" onClick={() => setFilterMode('filter')}>{t('sfc.ModeSelector.filterMode')}</Button><Button variant={filterMode === 'my-list' ? 'default' : 'outline'} size="sm" onClick={() => setFilterMode('my-list')}>{t('sfc.ModeSelector.myListMode')} {selectedSheets.length > 0 && <Badge>{selectedSheets.length}</Badge>}</Button>{filterMode === 'filter' ? <><Button variant="outline" size="sm" onClick={copyFilterLink}>↗</Button><Button variant="outline" size="sm" onClick={() => setFilters((current) => ({ ...current, superFilter: current.superFilter === null ? '' : null }))}>{t('term.superFilter')}</Button></> : <><Button variant="outline" size="sm" onClick={() => selectedSheets.length ? setExportOpen(true) : window.alert(t('sfc.ModeSelector.myListEmptyWarn'))}>{t('ui.download')}</Button><Button variant="outline" size="sm" onClick={() => void importSelectedSheets()}>↑</Button></>}</div><MyListExportDialog open={exportOpen} onOpenChange={setExportOpen} /></div>;
}
