// src/components/dialogs/MyListExportDialog.tsx
'use client';

import { useMemo } from 'react';
import { useTranslations } from 'next-intl';
import YAML from 'yaml';
import { saveAs } from 'file-saver';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useSelectedSheets } from '@/hooks/useSelectedSheets';
import { useGameContext } from '@/contexts/GameContext';

export function MyListExportDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { const t = useTranslations(); const { gameCode } = useGameContext(); const { selectedSheets } = useSelectedSheets(); const content = useMemo(() => YAML.stringify(selectedSheets.map((sheet) => sheet.sheetExpr)), [selectedSheets]); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{t('sfc.ModeSelector.exportMyList')}</DialogTitle></DialogHeader><Textarea readOnly value={content} className="min-h-64 font-mono" /><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>{t('ui.close')}</Button><Button onClick={() => saveAs(new Blob([content], { type: 'text/yaml;charset=utf-8' }), `${gameCode}-mylist-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}.yaml`)}>{t('ui.download')}</Button></DialogFooter></DialogContent></Dialog>; }

// components/dialogs/MyListExportDialog.vue
<script setup lang="ts">
import { computed } from '@nuxtjs/composition-api';
import YAML from 'yaml';
import FileSaver from 'file-saver';
import useDarkMode from '~/composables/useDarkMode';
import useGameInfo from '~/composables/useGameInfo';
import useSelectedSheets from '~/composables/useSelectedSheets';
import { toLocalISODateString } from '~/utils';

defineProps<{
  value: boolean;
}>();
// eslint-disable-next-line no-spaced-func, func-call-spacing
defineEmits<{
  (event: 'input', value: boolean): void;
}>();

const { isDarkMode } = useDarkMode();
const { gameCode } = useGameInfo();
const { selectedSheets } = useSelectedSheets();

const selectedSheetsYaml = computed(
  () => YAML.stringify(
    selectedSheets.value
      .map((sheet) => sheet.sheetExpr)
      .filter((sheetExpr) => sheetExpr != null),
  ),
);

async function exportSelectedSheets() {
  try {
    FileSaver.saveAs(
      new Blob([selectedSheetsYaml.value], { type: 'application/yaml; charset=utf-8;' }),
      `${gameCode.value}-mylist-${toLocalISODateString(new Date()).replaceAll('-', '')}.yaml`,
    );
  } catch (err) {
    // eslint-disable-next-line no-alert
    window.alert(`An error occurred while saving MY LIST:\n${err}`);
  }
}
</script>

<template>
  <v-dialog
    :value="value"
    max-width="600px"
    scrollable
    :overlay-color="isDarkMode ? '#FFF8' : undefined"
    @input="$emit('input', $event);"
  >
    <v-card>
      <v-card-title>
        <v-icon left>
          mdi-download
        </v-icon>
        {{ $t('sfc.ModeSelector.exportMyList') }}
      </v-card-title>
      <v-card-text>
        <v-textarea
          :label="`${$t('ui.preview')} (YAML)`"
          :value="selectedSheetsYaml"
          outlined
          readonly
          auto-grow
          hide-details
          class="mt-2"
          style="font-family: Consolas, monospace;"
        />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn
          text
          color="primary"
          @click="exportSelectedSheets"
        >
          {{ $t('ui.download') }}
        </v-btn>
        <v-btn
          text
          color="success"
          @click="$emit('input', false);"
        >
          {{ $t('ui.close') }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
