// src/components/dialogs/SheetComboDialog.tsx
"use client";

import { useEffect, useMemo } from "react";
import { useTranslations } from "next-intl";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { SheetTile } from "@/components/SheetTile";
import {
  useSheetComboAllowDuplicateStore,
  useSheetComboDialogStore,
  useSheetComboDrawSizeStore,
} from "@/stores/sheetComboDialog";
import { useSheetDialogStore } from "@/stores/sheetDialog";
import { useItemDrawer } from "@/hooks/useItemDrawer";
import { clamp } from "@/lib/utils/math";
import { NULL_SHEET, VOID_SHEET } from "@/lib/utils/sheet";
import type { Sheet } from "@/types";

export function SheetComboDialog() {
  const t = useTranslations();
  const state = useSheetComboDialogStore();
  const drawSize = useSheetComboDrawSizeStore((store) => store.value);
  const setDrawSize = useSheetComboDrawSizeStore((store) => store.setValue);
  const allowDuplicate = useSheetComboAllowDuplicateStore(
    (store) => store.value,
  );
  const setAllowDuplicate = useSheetComboAllowDuplicateStore(
    (store) => store.setValue,
  );
  const pool = useMemo(() => state.currentSheets, [state.currentSheets]);
  const openSheet = useSheetDialogStore((store) => store.open);
  const drawer = useItemDrawer<Sheet>({
    drawingPool: pool,
    drawSize,
    allowDuplicate,
  });
  const singleDrawer = useItemDrawer<Sheet>({ drawingPool: pool, drawSize: 1 });
  const { startDrawing } = drawer;
  useEffect(() => {
    if (state.isOpened && state.isDrawMode) void startDrawing();
  }, [startDrawing, state.isOpened, state.isDrawMode]);
  const sheets = state.isDrawMode
    ? drawer.currentItems.map((sheet) => sheet ?? NULL_SHEET)
    : state.currentSheets;
  const displaySheets = state.isShowAll ? sheets : sheets.slice(0, 100);
  const maxDialogWidth =
    displaySheets.length <= 4
      ? 400
      : displaySheets.length <= 9
        ? 550
        : displaySheets.length <= 16
          ? 700
          : displaySheets.length <= 25
            ? 850
            : displaySheets.length <= 36
              ? 1000
              : displaySheets.length <= 49
                ? 1150
                : displaySheets.length <= 64
                  ? 1300
                  : displaySheets.length <= 81
                    ? 1450
                    : 1600;
  const updateDrawSize = () => {
    const value = window.prompt(
      t("sfc.SheetComboDialog.changeDrawSize"),
      String(drawSize),
    );
    if (value != null) setDrawSize(clamp(Number(value) || drawSize, 1, 100));
  };
  const drawOneFromPool = async () => {
    if (!pool.length) {
      window.alert(t("description.drawPoolEmpty"));
      return;
    }
    await singleDrawer.startDrawing((items) => {
      if (items[0]) openSheet(items[0], true);
    });
  };
  return (
    <Dialog
      open={state.isOpened}
      onOpenChange={(open) => {
        if (!open) {
          void drawer.stopDrawing();
          void singleDrawer.stopDrawing();
          state.close();
        }
      }}
    >
      <DialogContent
        className="max-w-[96vw]"
        style={{ width: `min(${maxDialogWidth}px, 96vw)` }}
      >
        <DialogHeader>
          <DialogTitle>
            {state.isDrawMode ? (
              t("sfc.SheetComboDialog.drawResults")
            ) : (
              <>
                {state.headerTitle ?? t("sfc.SheetComboDialog.drawResults")} (
                {t("sfc.FilterInfoBar.sheetsCount", {
                  n: state.currentSheets.length,
                })}
                )
              </>
            )}
          </DialogTitle>
        </DialogHeader>
        {state.isDrawMode && (
          <div className="flex flex-wrap items-center gap-4 text-sm">
            <label className="flex items-center gap-2">
              <Switch
                checked={allowDuplicate}
                onCheckedChange={setAllowDuplicate}
              />
              {t("sfc.SheetComboDialog.allowDuplicate")}
            </label>
            <label className="flex items-center gap-2">
              <Switch
                checked={state.isBlindfoldMode}
                onCheckedChange={state.setBlindfoldMode}
              />
              {t("sfc.SheetComboDialog.blindfoldMode")}
            </label>
            <Button variant="outline" onClick={updateDrawSize}>
              {drawSize}
            </Button>
          </div>
        )}
        <div
          className="mt-5 flex flex-wrap justify-center gap-2"
          onContextMenu={(event) => event.preventDefault()}
        >
          {displaySheets.map((sheet, index) => (
            <div key={`${sheet.sheetExpr ?? sheet.songNo}-${index}`}>
              {state.isBlindfoldMode && !state.blindfoldedIndexes.has(index) ? (
                <SheetTile
                  sheet={VOID_SHEET}
                  hideTitle
                  onClick={() => state.reveal(index)}
                />
              ) : (
                <SheetTile sheet={sheet} />
              )}
            </div>
          ))}
        </div>
        {!state.isShowAll && sheets.length > 100 && (
          <Button
            variant="link"
            onClick={() =>
              useSheetComboDialogStore.setState({ isShowAll: true })
            }
          >
            {t("ui.showAll")}
          </Button>
        )}
        <DialogFooter>
          {state.isDrawPool && !state.isDrawMode && (
            <Button
              variant="outline"
              onClick={() => void drawOneFromPool()}
              disabled={singleDrawer.isDrawing}
            >
              {t("sfc.SheetDrawerPanel.drawRandomSheet")}
            </Button>
          )}
          {state.isDrawMode && (
            <Button
              variant="outline"
              onClick={() => void drawer.startDrawing()}
            >
              {t("sfc.SheetDialog.tryAgain")}
            </Button>
          )}
          <Button
            onClick={() => {
              void drawer.stopDrawing();
              void singleDrawer.stopDrawing();
              state.close();
            }}
          >
            {state.isDrawMode ? t("ui.ok") : t("ui.close")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// components/dialogs/SheetComboDialog.vue
<script setup lang="ts">
import { computed, watch } from '@nuxtjs/composition-api';
import useI18n from '~/composables/useI18n';
import useDarkMode from '~/composables/useDarkMode';
import useSheetDialog from '~/composables/useSheetDialog';
import useSheetComboDialog from '~/composables/useSheetComboDialog';
import SheetTile from '~/components/SheetTile.vue';
import { clamp, VOID_SHEET } from '~/utils';

const i18n = useI18n();
const { isDarkMode } = useDarkMode();
const {
  viewSheet,
} = useSheetDialog();
const {
  currentSheets,
  isOpened,
  isDrawMode,
  isDrawPool,
  isStatic,
  isShowAll,
  headerTitle,
  drawSize,
  allowDuplicate,
  startDrawingSheetCombo,
  stopDrawingSheetCombo,
  isBlindfoldMode,
  blindfoldedIndexes,
} = useSheetComboDialog();
const {
  drawingPool: sheetDrawingPool,
  startDrawingSheet,
} = useSheetDialog();

const displayingSheets = computed(() => (
  isShowAll.value
    ? currentSheets.value
    : currentSheets.value.slice(0, 100)
));

async function drawSheet() {
  if (currentSheets.value.length === 0) {
    // eslint-disable-next-line no-alert
    window.alert(i18n.t('description.drawPoolEmpty'));
    return;
  }

  sheetDrawingPool.value = currentSheets.value;
  await startDrawingSheet();
}

async function drawSheets() {
  await startDrawingSheetCombo();
}

function configDrawSize() {
  // eslint-disable-next-line no-alert
  const userInput = window.prompt('Input draw size (1~100):', String(drawSize.value));

  if (userInput === null) return;

  const newDrawSize = Number(userInput);

  if (!Number.isInteger(newDrawSize)) {
    // eslint-disable-next-line no-alert
    window.alert('Invalid draw size.');
    return;
  }

  drawSize.value = clamp(newDrawSize, 1, 100);
}

function handleSheetClick(index: number) {
  if (blindfoldedIndexes.value.has(index)) {
    // reveal sheet
    blindfoldedIndexes.value.delete(index);
    blindfoldedIndexes.value = new Set(blindfoldedIndexes.value);
  } else {
    viewSheet(currentSheets.value[index]);
  }
}

const maxDialogWidth = computed(() => {
  const displayCount = displayingSheets.value.length;

  // 2 per line
  if (displayCount <= 4) return 400;
  // 3 per line
  if (displayCount <= 9) return 550;
  // 4 per line
  if (displayCount <= 16) return 700;
  // 5 per line
  if (displayCount <= 25) return 850;
  // 6 per line
  if (displayCount <= 36) return 1000;
  // 7 per line
  if (displayCount <= 49) return 1150;
  // 8 per line
  if (displayCount <= 64) return 1300;
  // 9 per line
  if (displayCount <= 81) return 1450;
  // 10 per line
  return 1600;
});

watch(isOpened, () => {
  if (!isOpened.value) stopDrawingSheetCombo();
});
</script>

<template>
  <v-dialog
    v-model="isOpened"
    :max-width="maxDialogWidth"
    :overlay-color="isDarkMode ? '#FFF8' : undefined"
    scrollable
  >
    <v-card>
      <v-card-title class="justify-center text-center">
        <template v-if="isDrawMode">
          {{ $t('sfc.SheetComboDialog.drawResults') }}
        </template>
        <template v-else>
          {{ headerTitle }}
          <br>
          ({{ $t('sfc.FilterInfoBar.sheetsCount', { n: currentSheets.length }) }})
        </template>
      </v-card-title>

      <v-divider class="mx-4" />

      <div class="py-5 overflow-y-auto" style="overscroll-behavior: contain;">
        <div
          class="d-flex flex-wrap justify-center"
          style="gap: 8px;"
          @contextmenu.prevent
        >
          <SheetTile
            v-for="(sheet, i) in displayingSheets"
            :key="i"
            :sheet="!blindfoldedIndexes.has(i) ? sheet : VOID_SHEET"
            :hide-cover="!isStatic"
            @click.left="handleSheetClick(i);"
          />
        </div>
        <div class="d-flex justify-center py-4">
          <v-btn
            v-if="displayingSheets.length < currentSheets.length"
            color="info"
            outlined
            @click="isShowAll = true;"
          >
            {{ $t('ui.showAll') }}
          </v-btn>
        </div>
      </div>

      <v-divider class="mx-4" />

      <v-card-actions>
        <template v-if="isDrawMode">
          <!-- Draw Count -->
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                large
                icon
                class="text-h6 pa-0 ma-0"
                @click="configDrawSize();"
                v-on="on"
              >
                <v-icon>mdi-pound-box-outline</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetComboDialog.changeDrawSize')" />
          </v-tooltip>

          <!-- No Duplicate -->
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                large
                icon
                class="text-h6 pa-0 ma-0"
                @click="allowDuplicate = !allowDuplicate;"
                v-on="on"
              >
                <v-icon>{{ allowDuplicate ? 'mdi-autorenew' : 'mdi-autorenew-off' }}</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetComboDialog.allowDuplicate')" />
          </v-tooltip>

          <!-- Blindfold Mode -->
          <v-tooltip top>
            <template #activator="{ on }">
              <v-btn
                large
                icon
                class="text-h6 pa-0 ma-0"
                @click="isBlindfoldMode = !isBlindfoldMode;"
                v-on="on"
              >
                <v-icon>{{ !isBlindfoldMode ? 'mdi-eye' : 'mdi-eye-off' }}</v-icon>
              </v-btn>
            </template>
            <span v-text="$t('sfc.SheetComboDialog.blindfoldMode')" />
          </v-tooltip>
        </template>
        <template v-if="isDrawPool">
          <v-btn
            text
            color="primary"
            @click="drawSheet();"
          >
            {{ $t('sfc.SheetDrawerPanel.drawRandomSheet') }}
          </v-btn>
        </template>

        <v-spacer />

        <v-btn
          v-if="isDrawMode"
          text
          color="primary"
          @click="drawSheets();"
        >
          {{ $t('sfc.SheetDialog.tryAgain') }}
        </v-btn>
        <v-btn
          text
          color="success"
          @click="isOpened = false;"
        >
          {{ isDrawMode ? $t('ui.ok') : $t('ui.close') }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>
