// src/components/dialogs/SheetDialog.tsx
'use client';

import { useEffect, useState } from 'react';
import { useTranslations } from 'next-intl';
import { mdiBookmark, mdiBookmarkCheck, mdiCircleOffOutline, mdiContentCopy, mdiDomainOff, mdiEarthBoxOff, mdiEarthOff, mdiLock, mdiOpenInNew, mdiSignalOff } from '@mdi/js';
import copyToClipboard from 'copy-to-clipboard';
import catImage from '@/assets/images/cat.png';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Icon } from '@/components/Icon';
import { useSheetDialogStore } from '@/stores/sheetDialog';
import { useSelectedSheets } from '@/hooks/useSelectedSheets';
import { useGameLookups } from '@/hooks/useGameLookups';
import { getCanonicalSheet } from '@/lib/utils/sheet';
import { cn } from '@/lib/cn';

const regionIconPaths: Record<string, string> = {
  jp: mdiCircleOffOutline,
  intl: mdiEarthOff,
  usa: mdiDomainOff,
  cn: mdiEarthBoxOff,
  offline: mdiSignalOff,
};

export function SheetDialog() {
  const t = useTranslations();
  const { isOpened, currentSheet, isDrawMode, close } = useSheetDialogStore();
  const open = useSheetDialogStore((state) => state.open);
  const { selectedSheetSet, toggleSheetSelection } = useSelectedSheets();
  const lookup = useGameLookups();
  const [failedImage, setFailedImage] = useState<string | null>(null);

  useEffect(() => {
    setFailedImage(null);
  }, [currentSheet]);

  if (!currentSheet) return null;
  const canonicalSheet = getCanonicalSheet(currentSheet);
  const imageError = failedImage === currentSheet.imageUrl;
  const imageSrc = imageError ? catImage.src : (currentSheet.imageUrl ?? catImage.src);
  const searchUrl = lookup.getSheetSearchLink(currentSheet);
  const difficultyIcon = lookup.getDifficultyIconUrl(currentSheet.difficulty);
  const typeIcon = lookup.getTypeIconUrl(currentSheet.type);

  const copyTitle = () => {
    if (currentSheet.title == null) return;
    copyToClipboard(currentSheet.title);
    window.alert(t('description.copied'));
  };

  return <Dialog open={isOpened} onOpenChange={(value) => { if (!value) close(); }}><DialogContent className="w-[min(96vw,760px)]"><DialogHeader><DialogTitle>{currentSheet.title}</DialogTitle></DialogHeader><div className={cn('relative mx-auto w-full max-w-[500px] overflow-hidden rounded bg-gray-300 p-3 dark:bg-gray-700', currentSheet.isSpecial && 'rainbow-background')}><img src={imageSrc} alt={currentSheet.title ?? ''} className="mx-auto max-h-[52vh] w-full object-contain" onError={() => setFailedImage(currentSheet.imageUrl ?? null)} /><div className="absolute right-3 top-3"><Button variant="outline" size="icon" className="bg-white/80 dark:bg-black/50" onClick={() => toggleSheetSelection(canonicalSheet)} aria-label="Toggle My List"><Icon path={selectedSheetSet.has(canonicalSheet) ? mdiBookmarkCheck : mdiBookmark} /></Button></div>{typeIcon && <img src={typeIcon} alt="" className="absolute bottom-4 left-4" />}</div><div className="grid gap-5 pt-2 md:grid-cols-[1fr_auto] md:items-start"><div className="min-w-0"><button type="button" className="block max-w-full truncate text-left text-sm opacity-75" onClick={copyTitle}>{(currentSheet.category ?? 'N/A').replaceAll('|', '｜')}</button><button type="button" className="block max-w-full truncate py-2 text-left text-2xl font-semibold" onClick={copyTitle} title={currentSheet.title ?? undefined}>{currentSheet.title}</button><p className="truncate pb-2 font-medium">{currentSheet.artist ?? 'N/A'}</p><p className="flex items-center gap-1 py-2 text-xl font-semibold" style={{ color: lookup.getDifficultyColor(currentSheet.difficulty) }}>{difficultyIcon && <img src={difficultyIcon} height={lookup.getDifficultyIconHeight(currentSheet.difficulty)} alt="" />}{lookup.getDifficultyName(currentSheet.difficulty)} {currentSheet.level}{currentSheet.internalLevel != null && <small className="text-sm opacity-70">({currentSheet.internalLevel})</small>}</p><p className="pt-2 text-sm"><strong>{t('term.noteDesigner')}:</strong> {currentSheet.noteDesigner ?? 'N/A'}</p><p className="pt-2 text-sm"><strong>{t('term.releaseDate')}:</strong> {currentSheet.releaseDate ?? '????-??-??'} ({currentSheet.version ?? 'N/A'})</p><p className="pt-2 text-sm"><strong>{t('term.comment')}:</strong> {currentSheet.comment ?? 'N/A'}</p></div><div className="flex flex-row items-start gap-2 md:flex-col md:items-end"><strong>{t('term.bpm')} {currentSheet.bpm ?? '?'}</strong>{currentSheet.isLocked && <span title={t('description.unlockNeeded')}><Icon path={mdiLock} size={28} /></span>}{lookup.data.regions.map((region) => { if (currentSheet.regions?.[region.region] !== false) return null; return <span key={region.region} title={t('description.unavailableInRegion', { region: region.name })} style={{ transform: ['jp', 'usa', 'offline'].includes(region.region) ? undefined : 'rotateY(180deg)' }}><Icon path={regionIconPaths[region.region] ?? mdiCircleOffOutline} size={28} /></span>; })}</div></div><DialogFooter><div className="mr-auto flex gap-2">{searchUrl && <Button variant="outline" asChild><a href={searchUrl} target="_blank" rel="noreferrer"><Icon path={mdiOpenInNew} size={16} />{currentSheet.searchUrl ? ':3' : t('sfc.SheetDialog.searchOnYouTube')}</a></Button>}<Button variant="outline" onClick={copyTitle}><Icon path={mdiContentCopy} size={16} />{t('description.copied')}</Button></div>{isDrawMode && <Button variant="outline" onClick={() => open(currentSheet, true)}>{t('sfc.SheetDialog.tryAgain')}</Button>}<Button onClick={close}>{isDrawMode ? t('ui.ok') : t('ui.close')}</Button></DialogFooter><Badge className="mt-3">{currentSheet.sheetExpr ?? `${currentSheet.songId}|${currentSheet.type}|${currentSheet.difficulty}`}</Badge></DialogContent></Dialog>;
}

// components/dialogs/SheetDialog.vue
<script setup lang="ts">
import { ref, computed, watch } from '@nuxtjs/composition-api';
import copyToClipboard from 'copy-to-clipboard';
import { useDataStore } from '~/stores/data';
import useDarkMode from '~/composables/useDarkMode';
import useGameData from '~/composables/useGameData';
import useSelectedSheets from '~/composables/useSelectedSheets';
import useSheetDialog from '~/composables/useSheetDialog';
import { getCanonicalSheet } from '~/utils';
import catImageUrl from '~/assets/images/cat.png';

const dataStore = useDataStore();
const { isDarkMode } = useDarkMode();
const {
  getTypeIconUrl,
  getDifficultyName,
  getDifficultyColor,
  getDifficultyIconUrl,
  getDifficultyIconHeight,
  getSheetSearchLinkIcon,
  getSheetSearchLinkColor,
  getSheetSearchLink,
} = useGameData();
const {
  selectedSheets,
  toggleSheetSelection,
} = useSelectedSheets();
const {
  currentSheet: sheet,
  isOpened,
  isDrawMode,
  isStatic,
  startDrawingSheet,
  stopDrawingSheet,
} = useSheetDialog();

const imageErrorOccurred = ref(false);
const copyHintOpened = ref(false);

const data = computed(() => dataStore.currentData);
const imageSrc = computed(() => {
  if (imageErrorOccurred.value) return catImageUrl;
  return isStatic.value ? sheet.value.imageUrl : undefined;
});
const isSheetSelected = computed(
  () => selectedSheets.value.includes(getCanonicalSheet(sheet.value)),
);

function copyText(text: string | undefined) {
  if (text == null) return;

  copyToClipboard(text, {
    format: 'text/plain',
  });

  copyHintOpened.value = true;
}

async function drawSheet() {
  await startDrawingSheet();
}

watch(sheet, () => {
  imageErrorOccurred.value = false;
});
watch(isOpened, () => {
  if (!isOpened.value) stopDrawingSheet();
});
</script>

<template>
  <v-dialog
    v-model="isOpened"
    max-width="500px"
    :overlay-color="isDarkMode ? '#FFF8' : undefined"
  >
    <!-- This is explicitly added for the variables used in v-on to be exposed correctly -->
    <template v-if="false">
      {{ imageErrorOccurred }}
    </template>

    <v-card>
      <v-img
        :key="imageSrc"
        contain
        class="grey lighten-2"
        :class="{ 'rainbow-background': sheet.isSpecial }"
        :height="$vuetify.breakpoint.height < 750 ? '250px' : '350px'"
        :src="imageSrc"
        @error="imageErrorOccurred = true;"
      >
        <!-- invisible image for user to save -->
        <img
          :src="imageSrc"
          style="
            position: absolute;
            height: 100%; width: 100%;
            object-fit: contain;
            opacity: 0;
            vertical-align: middle;"
          :title="sheet.title"
          alt=""
        >

        <div
          v-if="!isStatic"
          class="d-flex justify-center align-center fill-height text-h1 white--text"
        >
          <span v-text="sheet.songNo" />
        </div>

        <div
          class="d-flex flex-column pa-3"
          style="position: absolute; top: 0; right: 0; gap: 8px;"
        >
          <v-btn
            fab
            large
            class="teal--text"
            @click="toggleSheetSelection(getCanonicalSheet(sheet));"
          >
            <v-icon large>
              {{ isSheetSelected ? 'mdi-bookmark-check' : 'mdi-bookmark-plus-outline' }}
            </v-icon>
          </v-btn>
        </div>

        <div
          class="d-flex flex-column pa-3"
          style="position: absolute; bottom: 0; right: 0; gap: 8px;"
        >
          <v-tooltip v-if="sheet.searchUrl !== null" top>
            <template #activator="{ on }">
              <v-btn
                :fab="$vuetify.breakpoint.xsOnly"
                :text="$vuetify.breakpoint.smAndUp"
                :color="getSheetSearchLinkColor(sheet)"
                :href="getSheetSearchLink(sheet)"
                target="_blank"
                class="white--text"
                v-on="on"
              >
                <v-icon :large="$vuetify.breakpoint.smAndUp">
                  {{ getSheetSearchLinkIcon(sheet) }}
                </v-icon>
              </v-btn>
            </template>
            <span>
              {{ sheet.searchUrl === undefined ? $t('sfc.SheetDialog.searchOnYouTube') : ':3' }}
            </span>
          </v-tooltip>
        </div>

        <img
          v-if="getTypeIconUrl(sheet.type) != null"
          :src="getTypeIconUrl(sheet.type)"
          style="position: absolute; bottom: 10px; left: 15px;"
          alt=""
        >
      </v-img>
      <v-card-text class="py-5">
        <div style="position: relative;">
          <!-- Left column -->
          <div>
            <!-- Category -->
            <h3
              class="text-truncate"
              style="margin-right: 80px;"
            >
              <span>{{ (sheet.category ?? 'N/A').replaceAll('|', '｜') }}</span>
            </h3>

            <!-- Title -->
            <v-tooltip top>
              <template #activator="{ on }">
                <h1
                  class="py-2 text-truncate"
                  :class="{ 'text--primary': isStatic }"
                  style="cursor: pointer; user-select: all; margin-right: 42px;"
                  v-on="on"
                  @click="copyText(sheet.title);"
                >
                  <span v-text="sheet.title" />
                </h1>
              </template>
              <span v-text="sheet.title" />
            </v-tooltip>

            <!-- Artist -->
            <h4
              class="pb-2 text-truncate"
              style="margin-right: 42px;"
            >
              <span>{{ sheet.artist ?? 'N/A' }}</span>
            </h4>

            <!-- Difficulty & Level -->
            <h2 class="py-2 text-truncate">
              <img
                v-if="getDifficultyIconUrl(sheet.difficulty) != null"
                :src="getDifficultyIconUrl(sheet.difficulty)"
                :height="getDifficultyIconHeight(sheet.difficulty)"
                class="mr-1"
                alt=""
                style="vertical-align: middle;"
              >
              <span
                :class="{ 'text--primary': getDifficultyColor(sheet.difficulty) === 'unset' }"
                :style="{ 'color': getDifficultyColor(sheet.difficulty) }"
              >{{ getDifficultyName(sheet.difficulty) }} {{ sheet.level }}</span>
              <v-tooltip top>
                <template #activator="{ on }">
                  <small
                    class="text--secondary"
                    :style="{ 'visibility': sheet.internalLevel != null ? 'visible' : 'hidden' }"
                    v-on="on"
                  >
                    <span>({{ sheet.internalLevel }})</span>
                  </small>
                </template>
                <span v-text="$t('term.internalLevel')" />
              </v-tooltip>
            </h2>

            <!-- Note Designer -->
            <h4 class="pt-2 text-truncate">
              <span v-text="$t('term.noteDesigner')" />:
              <span>{{ sheet.noteDesigner ?? 'N/A' }}</span>
            </h4>

            <!-- Release Date & Version -->
            <h4 class="pt-2 text-truncate">
              <span v-text="$t('term.releaseDate')" />:
              <span>{{ sheet.releaseDate ?? '????-??-??' }}</span>
              <span>({{ sheet.version ?? 'N/A' }})</span>
            </h4>

            <!-- Comment -->
            <h4 class="pt-2 text-truncate">
              <span v-text="$t('term.comment')" />:
              <span>{{ sheet.comment ?? 'N/A' }}</span>
            </h4>
          </div>

          <!-- Right column -->
          <div
            class="d-flex flex-column justify-start align-end"
            style="position: absolute; top: 0; right: 0;"
          >
            <!-- BPM -->
            <h3 class="mb-2">
              <span v-text="$t('term.bpm')" />
              <span>{{ sheet.bpm != null ? sheet.bpm : '?' }}</span>
            </h3>

            <!-- Unlock needed -->
            <v-tooltip v-if="sheet.isLocked" top>
              <template #activator="{ on }">
                <v-icon large class="pa-1" v-on="on">
                  mdi-lock
                </v-icon>
              </template>
              <span v-text="$t('description.unlockNeeded')" />
            </v-tooltip>

            <!-- Unavailable in regions -->
            <template v-for="{ region, name: regionName }, i in data.regions">
              <v-tooltip
                v-if="sheet.regions && sheet.regions[region] === false"
                :key="i"
                top
              >
                <template #activator="{ on }">
                  <v-icon
                    large
                    class="pa-1"
                    :style="{
                      'transform': !['jp', 'usa', 'offline'].includes(region)
                        ? 'rotateY(180deg)'
                        : 'none',
                    }"
                    v-on="on"
                  >
                    {{ region === 'jp' ? 'mdi-circle-off-outline' : '' }}
                    {{ region === 'intl' ? 'mdi-earth-off' : '' }}
                    {{ region === 'usa' ? 'mdi-domain-off' : '' }}
                    {{ region === 'cn' ? 'mdi-earth-box-off' : '' }}
                    {{ region === 'offline' ? 'mdi-signal-off' : '' }}
                  </v-icon>
                </template>
                <span>
                  {{ $t('description.unavailableInRegion', { region: regionName }) }}
                </span>
              </v-tooltip>
            </template>
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn
          v-if="isDrawMode"
          text
          color="primary"
          @click="drawSheet();"
        >
          {{ $t('sfc.SheetDialog.tryAgain') }}
        </v-btn>
        <v-btn
          text
          color="success"
          @click="isOpened = false;"
        >
          {{ isDrawMode ? $t('ui.ok') : $t('ui.close') }}
        </v-btn>
      </v-card-actions>
    </v-card>

    <v-snackbar v-model="copyHintOpened" :timeout="750">
      <v-icon left color="success">
        mdi-content-copy
      </v-icon>
      <span v-text="$t('description.copied')" />
    </v-snackbar>
  </v-dialog>
</template>
