// components/dialogs/SuperFilterDialog.vue
<script setup lang="ts">
import { ref, watchEffect } from '@nuxtjs/composition-api';
import useDarkMode from '~/composables/useDarkMode';
import useGameInfo from '~/composables/useGameInfo';
import { parseSuperFilter } from '~/utils';

const props = defineProps<{
  value: boolean;
  superFilterText: string;
}>();
// eslint-disable-next-line no-spaced-func, func-call-spacing
defineEmits<{
  (event: 'input', value: boolean): void;
  (event: 'update:superFilterText', value: string): void;
}>();

const { isDarkMode } = useDarkMode();
const { dataSourceUrl } = useGameInfo();

const currentSuperFilterText = ref('');

function validateSuperFilter(superFilterText: string): boolean | string {
  try {
    const superFilter = parseSuperFilter(superFilterText);

    if (typeof superFilter !== 'function') throw new TypeError('You should return a predicate function.');

    return true;
  } catch (err) {
    return String(err);
  }
}

watchEffect(() => {
  if (props.value) {
    currentSuperFilterText.value = props.superFilterText;
  }
});
</script>

<template>
  <v-dialog
    :value="value"
    max-width="600px"
    scrollable
    :overlay-color="isDarkMode ? '#FFF8' : undefined"
    @input="$emit('input', $event);"
  >
    <v-card>
      <v-card-title>
        <v-icon left>
          mdi-code-braces-box
        </v-icon>
        <span>
          {{ $t('term.superFilter') }} (JavaScript)
        </span>
      </v-card-title>
      <v-card-text class="py-0">
        <fieldset class="rounded pb-1 mb-4">
          <legend class="px-1 ml-2">
            <v-icon small>
              mdi-information-outline
            </v-icon>
            <span>Instructions</span>
          </legend>
          <ul>
            <li>
              <code>sheet</code>
              is of type
              <a href="https://github.com/zetaraku/arcade-songs/blob/master/types/Sheet.ts" target="_blank"><code>Sheet</code></a>
              and has all properties of the
              <a href="https://github.com/zetaraku/arcade-songs/blob/master/types/Song.ts" target="_blank"><code>Song</code></a>
              it belongs to.
            </li>
            <li>
              You can also refer to the
              <code>songs</code>
              property in the
              <a :href="`${dataSourceUrl}/data.json`" target="_blank">Current Data Source</a>.
            </li>
            <li>
              👉 <a href="https://gist.github.com/zetaraku/e2dab92b65ca2e0166f61f44fca16547" target="_blank">Examples</a>
            </li>
            <li>
              <b>DO NOT paste any code that you cannot trust or understand!</b>
            </li>
          </ul>
        </fieldset>
        <v-textarea
          v-model="currentSuperFilterText"
          rows="5"
          :rules="[validateSuperFilter]"
          label="function getSuperFilter() {"
          :placeholder="$t('description.superFilterPlaceholder')"
          :hint="$t('description.superFilterHint')"
          persistent-placeholder
          outlined
          auto-grow
          style="font-family: Consolas, monospace;"
        />
      </v-card-text>
      <v-card-actions>
        <v-spacer />
        <v-btn
          text
          color="secondary"
          @click="$emit('input', false);"
        >
          {{ $t('ui.cancel') }}
        </v-btn>
        <v-btn
          text
          color="success"
          @click="
            $emit('update:superFilterText', currentSuperFilterText);
            $emit('input', false);
          "
        >
          {{ $t('ui.ok') }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

// src/components/dialogs/SuperFilterDialog.tsx
'use client';

import { useEffect, useMemo, useState } from 'react';
import { useTranslations } from 'next-intl';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { useGameContext } from '@/contexts/GameContext';
import { parseSuperFilter } from '@/lib/utils/filter';

export function SuperFilterDialog({ open, onOpenChange, value, onCommit }: { open: boolean; onOpenChange: (open: boolean) => void; value: string; onCommit: (value: string) => void }) {
  const t = useTranslations();
  const { dataSourceUrl } = useGameContext();
  const [draft, setDraft] = useState(value);
  useEffect(() => { if (open) setDraft(value); }, [open, value]);
  const error = useMemo(() => {
    if (!draft) return '';
    try {
      const result = parseSuperFilter(draft);
      return typeof result === 'function' ? '' : 'You should return a predicate function.';
    } catch (err) {
      return String(err);
    }
  }, [draft]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{t('term.superFilter')} (JavaScript)</DialogTitle><DialogDescription>{t('description.superFilterHint')}</DialogDescription></DialogHeader><ul className="list-disc space-y-1 pl-5 text-sm"><li><code>sheet</code> is a <a className="text-blue-600 underline" href="https://github.com/zetaraku/arcade-songs/blob/master/types/Sheet.ts" target="_blank" rel="noreferrer"><code>Sheet</code></a> with the properties of its <a className="text-blue-600 underline" href="https://github.com/zetaraku/arcade-songs/blob/master/types/Song.ts" target="_blank" rel="noreferrer"><code>Song</code></a>.</li><li>You can refer to the <code>songs</code> property in the <a className="text-blue-600 underline" href={`${dataSourceUrl}/data.json`} target="_blank" rel="noreferrer">Current Data Source</a>.</li><li><a className="text-blue-600 underline" href="https://gist.github.com/zetaraku/e2dab92b65ca2e0166f61f44fca16547" target="_blank" rel="noreferrer">Examples</a></li><li><strong>Do not paste code that you cannot trust or understand.</strong></li></ul><Textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={t('description.superFilterPlaceholder')} className="font-mono" />{error && <p className="mt-2 text-sm text-red-600">{error}</p>}<DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>{t('ui.cancel')}</Button><Button disabled={Boolean(error)} onClick={() => { onCommit(draft); onOpenChange(false); }}>{t('ui.ok')}</Button></DialogFooter></DialogContent></Dialog>;
}
